.travis.yml
This adds basic travis configuration.
=> zincati: setup travis

dist/examples/00-config-sample.toml, src/config/fragments.rs, src/config/inputs.rs, src/config/mod.rs, src/identity/mod.rs, src/main.rs
This adds basic support for TOML configuration.
=> config: add TOML inputs

src/main.rs
This aborts the whole process whenever an actix actor panics.
=> zincati: abort process on actor panic

dist/sysusers.d/50-zincati.conf
Closes: https://github.com/coreos/zincati/issues/7
=> dist: add zincati user via sysusers

COPYRIGHT, DCO, LICENSE, README.md
This adds basic documentations and licensing information.
=> docs: add README and copyright references

Cargo.lock, Cargo.toml
zincati 0.0.1:
* initial release
=> Release 0.0.1

src/update_agent/mod.rs
This adds some instrumentation to update-agent state machine, so that
its internal state and last transition can be observed externally.
=> update-agent: observe state changes

src/rpm_ostree/cli_deploy.rs
This records some metrics on 'rpm-ostree deploy' runs, including total
attempts and failures.
=> rpm_ostree/deploy: record metrics

src/main.rs, src/metrics/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
This adjusts few minor log messages and levels, uniforming them.
=> zincati: tweak logging

src/update_agent/actor.rs
This augments logging at the default level in order to show when
(possibly long-running) rpm-ostree transactions start.
=> update_agent: log relevant transaction events

src/identity/mod.rs
This adds a metrics gauge to track and expose user-configured
rollout wariness.
=> identity: track rollout wariness in metrics

src/cincinnati/mod.rs, src/update_agent/actor.rs
This contains minor fixes and improvements to logging and metrics
tracking.
=> zincati: improve logging and metrics

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md
Adds a feature template per meeting.
/cc @darkmuggle @ajeddeloh @lucab @vrutkovs @arithx
=> github: add feature template

src/identity/mod.rs
This expose an info metrics with OS version, which can be thus used
by external observers to track auto-updates progress across a fleet
of machine. The final metrics looks like this:
```
zincati_identity_os_version{value="30.20190905.0"} 1
```
Ref: https://github.com/coreos/zincati/issues/120
=> identity: expose OS version metrics

src/rpm_ostree/cli_deploy.rs
This relaxes the deploy logic in order to better behave in cases
where the target revision is already staged locally.
This acknowledges the fact that `rpm-ostree deploy` is using
`77` as a positive exit-code to signal that no changes had to be
performed.
Closes: https://github.com/coreos/zincati/issues/124
=> rpm_ostree/deploy: do not error on exit code 77

src/fleet_lock/mock_tests.rs, src/fleet_lock/mod.rs
This updates the FleetLock client for a last-minute change in protocol
parameters naming.
=> fleet_lock: update protocol parameters

src/cincinnati/client.rs, src/cincinnati/mod.rs
This uniforms all Cincinnati-related logic to use a module-specific
error type. The intent is to make sure each failure can be recorded
with machine-friendly and human-friendly identifiers.
For server errors, it optionally tracks the status code too.
It also augments error metrics with the machine-friendly
kind. The resulting metrics now looks like this:
```
zincati_cincinnati_update_checks_errors_total{kind="generic_http_418"} 42
```
Which in turn can be aggregated and visualized like this:
=> cincinnati: uniform and instrument error kinds

src/cincinnati/mod.rs
This adds logic to evaluate and record whether the booted deployment
is a dead-end release from the point of view of auto-updates graph
(i.e. it cannot further auto-update).
As a dead-end release requires manual intervention to get out of its
stuck state, this piece of information has to be bubbled-up to
monitoring systems (e.g. via metrics).
Ref: https://github.com/coreos/zincati/issues/90
=> cincinnati: evaluate dead-end status for booted OS

.github/ISSUE_TEMPLATE/release-checklist.md, docs/usage/metrics.md
This contains a bunch of minor fixes to docpages.
=> docs: minor fixes

Cargo.lock, Cargo.toml
Changes:
* config: update FCOS Cincinnati endpoint (prod)
* docs: minor fixes
* ci: hook up to CoreOS CI
Tracker: https://github.com/coreos/zincati/milestone/7
=> Release 0.0.10

Cargo.lock, Cargo.toml, docs/usage/updates-strategy.md, src/config/fragments.rs, src/config/inputs.rs, src/config/mod.rs, src/main.rs, src/strategy/fleet_lock.rs, src/strategy/mod.rs, src/strategy/periodic.rs, src/weekly/mod.rs, src/weekly/utils.rs, tests/fixtures/00-config-sample.toml, tests/fixtures/20-periodic-sample.toml
This implements a new update strategy, with support for weekly maintenance windows.
Closes: https://github.com/coreos/zincati/issues/34
=> strategy: add logic for weekly maintenance windows

dist/config.d/30-updates-strategy.toml, docs/development/update-strategy-periodic.md
This adds some insights, rationale and history on the "periodic"
strategy.
=> docs/dev: add some details on periodic strategy design

.github/ISSUE_TEMPLATE/release-checklist.md
Reduce the diff with coreos-installer.  See https://github.com/coreos/coreos-installer/pull/257.
=> github: release checklist cleanups

docs/contributing.md, docs/development.md, docs/development/development.md, docs/development/os-metadata.md, docs/development/update-strategy-periodic.md, docs/usage.md, docs/usage/auto-updates.md, docs/usage/configuration.md, docs/usage/logging.md, docs/usage/metrics.md, docs/usage/updates-strategy.md
Preview: https://travier.github.io/zincati/
=> docs: Add contributing & simplify Jekyll front matter

src/main.rs
this gauges `process_start_time_seconds` following Prometheus conventions.
Fixes https://github.com/coreos/zincati/issues/119
=> metrics: expose process start timestamp

src/cincinnati/mod.rs
This rearranges the deadend refreshing logic so that metrics are always
refreshed, and internal state updated only after the change has been
persisted to MOTD. This allows retrying to persist the state on the next
graph update, in case of transient local errors.
It also inverts condition checks to properly account for ternary logic and
unknown state.
=> cincinnati: swap order of dead-end refreshing logic

.github/workflows/rust.yml, README.md
This updates CI toolchain and badge.
=> workflows/rust: update to latest stable toolchain 

Cargo.lock, Cargo.toml
Changes:
* identity: validate group settings
* workflows/rust: update to latest toolchain 
* config: set metrics values earlier
* docs/dev: add a quickstart guide
* strategy: record details on startup
* contrib: add dev container flow
* workflows/rust: avoid duplicated runs
* ci: move Travis jobs to GitHub actions
=> Release 0.0.15

Cargo.lock, Cargo.toml
Changes (from v0.0.15):
* github/release-checklist: generate vendor tarball too
* update-agent: expose current state via sd_notify
* tests/kola: fix recursive symlink
Trackers:
* https://github.com/coreos/zincati/milestone/13?closed=1
* https://github.com/coreos/zincati/milestone/14?closed=1
=> Release 0.0.17

src/rpm_ostree/cli_status.rs
Expose metrics for the number of deployments (excluding the booted
deployment and staged deployments). This is essentially the number
of deployments that are invalid candidates for targets of future
updates.
Also expose the total number of times Zincati attempted to query
local deployments (potentially utilizing the rpm-ostree actor's
cache), the total number of times `rpm-ostree status` was invoked,
and the total number of failed attempts to invoke `rpm-ostree status`.
=> rpm-ostree: expose metrics for status querying and caching

src/update_agent/mod.rs
This is already the case for UpdateAgent's `state_changed` field.
Change the `zincati_update_agent_latest_state_change_timestamp`
metric to not consider transitions into own state a "state change"
for consistency.
=> update_agent: don't consider transition into own state a "state change"

.github/workflows/rust.yml, src/cincinnati/client.rs, src/cli/agent.rs, src/fleet_lock/mod.rs, src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs, src/strategy/mod.rs, src/update_agent/mod.rs
This bumps linting toolchain to latest stable, and fixes new warnings.
Ref: https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps
Ref: https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
=> ci: bump linting toolchain

Cargo.lock, Cargo.toml, src/cincinnati/client.rs, src/cincinnati/mock_tests.rs, src/cli/agent.rs, src/dbus/experimental.rs, src/fleet_lock/mock_tests.rs, src/fleet_lock/mod.rs, src/metrics/mod.rs, src/rpm_ostree/mock_tests.rs, src/strategy/immediate.rs, src/strategy/periodic.rs
Bump tokio to 1.5, actix to 0.11, reqwest to 0.11 and massage some APIs.
Closes https://github.com/coreos/zincati/issues/518
=> Bump tokio, actix, reqwest

.cci.jenkinsfile, .github/ISSUE_TEMPLATE/release-checklist.md, .github/workflows/containers.yml, .github/workflows/rust.yml, README.md, docs/_config.yml, docs/development/quickstart.md, docs/development/testing.md, docs/index.md
Hold until cutover.
Includes changes for external repos that will be migrated around the same time.
=> *: rename master branch to main

src/update_agent/actor.rs, src/update_agent/mod.rs
The previous logic incorrectly causes the final reboot postponement
to be postponed for `DEFAULT_REFRESH_PERIOD_SECS`; more importantly,
it causes refresh tick delays of length
`DEFAULT_POSTPONEMENT_TIME_SECS` if update finalization is denied
due to update strategy constraints, potentially leading to much
more frequent finalization attempts.
We actually want the opposite of this behaviour.
=> update_agent: fix logic around reboot delays

src/strategy/mod.rs, src/update_agent/actor.rs
This adds metrics to measure the total number of finalization
attempts, `can_finalize` responses from  update strategy, and
attempts denied due to factors unrelated to update strategy,
such as active user sessions, or (in the future) systemd inhibitor
locks present.
Note: this is in addition to and distinct from the
`zincati_rpm_ostree_finalize_attempts_total`
`zincati_rpm_ostree_finalize_failures_total` metrics, as those two
metrics are solely related to the `rpm_ostree` actor and rpm-ostree
binary.
Closes https://github.com/coreos/zincati/issues/544.
=> Add more metrics around finalization attempts

src/update_agent/actor.rs, src/update_agent/mod.rs
We would like for everything under `UpdateAgentInfo` to be read-only.
Conceptually, it would make sense to put the `state_changed` field
behind the same lock as `UpdateAgentState`, but `UpdateAgentState` is
behind a `RwLock`, which doesn't allow for reads when it is acquired for
writing.
Get around this by manually ensuring that we only write to
`state_changed` when the `RwLock` that `UpdateAgentState` is behind is
acquired for writing. This allows us to ensure that the `RefCell` that
`state_changed` is behind will not panic, and also allows for reads even
when the `UpdateAgentState`'s `RwLock` is acquired for writing.
Addresses https://github.com/coreos/zincati/pull/577#discussion_r677072104 and closes https://github.com/coreos/zincati/issues/609.
=> update_agent: split `state_changed` out of `UpdateAgentInfo`

src/cincinnati/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
Previously, we had a read-only `UpdateAgentInfo` and a read-write
`UpdateAgentState` that was an enum representing the state of the
update agent in the state machine.
Rename this enum `UpdateAgentMachineState` and create a new struct
`UpdateAgentState` which encapsulates all the non-atomic read-write
data associated with the update agent. All this non-atomic read-write
data will be behind the RwLock.
Add a `denylist` field to this new read-write struct. During
initialization, save local finalized deployments to this denylist.
When fetching for new updates from Cincinnati, pass this denylist to
Cincinnati.
=> update_agent: record a denylist in the state of update agent

Cargo.lock
This is a routine lockfile update to shake off stale transitive dependencies.
=> lockfile: periodic refresh

.github/ISSUE_TEMPLATE/release-checklist.md, .github/dependabot.yml, .github/workflows/rust.yml
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@2d36a16f87ae9ed96780ae778b3ce410d76025e4.
=> Sync repo templates ⚙

Cargo.lock
Except zbus which is in https://github.com/coreos/zincati/pull/966
=> lockfile: Update many things

Cargo.lock
Need this release to include https://github.com/coreos/zincati/pull/1188, see check list https://github.com/coreos/zincati/issues/1190
=> cargo: update dependencies

.cci.jenkinsfile, Cargo.toml, Makefile
See individual commit messages.
=> Cargo.toml: stop setting debug=true for release profile; rework CI
