src/config/mod.rs, src/identity/mod.rs, src/main.rs
This adds a skeleton for runtime agent identity.
=> zincati: add agent identity

Cargo.lock, Cargo.toml, src/identity/mod.rs
This adds an hardcoded application ID (de35106b6ec24688b63afddaa156679b)
and uses it to get an app-specific node ID.
=> identity: add app-specific node ID

src/config/mod.rs, src/main.rs, src/strategy/immediate.rs, src/strategy/mod.rs
This adds update-strategy settings and "immediate" mode.
Immediate is the default update strategy. It fetches and
finalizes new updates immediately, regardless of maintenance
windows or cluster-wide orchestration.
It optionally allows to disable fetching or finalizing via
dedicated config options.
=> strategy: add immediate mode

src/main.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
This adds the main state-machine for the update agent.
The agent is modeled as an actix actor which periodically
tries to refresh its state-machine. It progresses through
individual states in order to check, fetch and finalize updates.
=> zincati: add agent state-machine

Cargo.lock, Cargo.toml, src/strategy/immediate.rs
This adds unit tests to cover the "immediate" strategy.
Async methods are tested via tokio current-thread runtime.
The full matrix of all configurable cases is covered via
proptest generation.
=> strategy/immediate: add unit tests

src/update_agent/actor.rs
This fixes a logic mistake that prevents the state-machine
from progressing after the first error. Instead, the next tick
should be scheduled regardless of the previous result.
=> agent: keep ticking the state-machine on errors

dist/examples/00-config-sample.toml, src/config/fragments.rs
This updates the TOML sample config, which now includes
a URL entry for Cincinnati.
=> config: update example with cincinnati URL

src/identity/mod.rs
This adds some methods on Identity to export agent parameters, in order to be consumed by the Cincinnati client.
=> identity: expose agent parameters

Cargo.lock, Cargo.toml, src/cincinnati/client.rs, src/cincinnati/mock_tests.rs, src/cincinnati/mod.rs, src/config/mod.rs, src/identity/mod.rs, src/main.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
This adds a Cincinnati client, which is used by the agent in order
to fetch update hints and progress its state machine.
=> cincinnati: support fetching update-hints

src/cincinnati/client.rs, src/cincinnati/mock_tests.rs
This fixes the media-type header on client request, according to
https://github.com/openshift/cincinnati/blob/master/docs/design/cincinnati.md#request
=> cincinnati: fix media-type header

Cargo.lock, Cargo.toml, src/main.rs, src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/cli_upgrade.rs, src/rpm_ostree/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
This adds an initial actor for rpm-ostree CLI client.
It also sketches the first step in downloading and applying updates.
=> rpm_ostree: add basic client-actor for upgrades

src/cincinnati/mock_tests.rs, src/identity/mod.rs, src/identity/platform.rs
This adds support for reading the Ignition platform ID from /proc/cmdline.
=> identity: read platform-id from kernel cmdline

Cargo.lock, Cargo.toml, src/identity/basearch.rs, src/identity/mod.rs
This adds logic for mapping from Rust target labels to Fedora
basearch labels.
=> identity: add support for non-amd64 base architectures

src/cincinnati/mod.rs, src/rpm_ostree/actor.rs, src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/cli_finalize.rs, src/rpm_ostree/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
This adds support for finalizing an OS update.
=> update_agent: add update finalization

src/cincinnati/mod.rs, src/identity/mod.rs, src/rpm_ostree/mod.rs
This switches the graph-lookup logic handling lookup in Cincinnati,
in order to use OS (base) checksum instead of version labels.
Closes: https://github.com/coreos/zincati/issues/25
=> cincinnati: lookup by OS checksum

src/cincinnati/mod.rs, src/rpm_ostree/mod.rs, src/update_agent/actor.rs
This defines a well-known metadata key to detect payload scheme,
and reserve the initial "checksum" kind.
Closes: https://github.com/coreos/zincati/issues/18
=> cincinnati: define payload scheme

src/config/fragments.rs, src/config/inputs.rs, src/strategy/immediate.rs, src/strategy/mod.rs, tests/fixtures/00-config-sample.toml
This removes existing config options for `strategy.immediate`. It
was deemed that these options don't have a strong-enough usecase
at this point, and it is easy to add them later if proper
requirements arise.
=> strategy/immediate: remove config options

Cargo.toml
This adds Cargo manifest metadata, in preparation for the first release.
=> cargo: add metadata

.travis.yml, Cargo.lock, Cargo.toml, dist/tmpfiles.d/zincati.conf, src/cincinnati/mod.rs, src/main.rs, src/metrics/mod.rs, src/update_agent/actor.rs
This adds a couple of initial metrics and a Prometheus exporter over a Unix-domain socket.
The socket is currently private, as metrics names are not stable and mostly meant for debugging (right now).
Closes: https://github.com/coreos/zincati/issues/27
=> zincati: add metrics collection and reporting

dist/config.d/50-fedora-coreos-cincinnati.toml
There was a last-minute change in the planned backend URL, due
to how fedora-infra production and staging DNS environments
are organized. This updates Zincati config to reflect such change.
=> config: update fedora-coreos backend URL

Cargo.lock, Cargo.toml, dist/tmpfiles.d/zincati.conf, src/config/inputs.rs, src/config/mod.rs
This updates configuration logic, dropping our custom file scanner and using [liboverdrop](https://docs.rs/liboverdrop/0.0.1/liboverdrop/struct.FragmentScanner.html#method.scan) instead.
=> config: use liboverdrop scanner 

Cargo.lock, Cargo.toml
* config: use liboverdrop scanner 
* config: update fedora-coreos backend URL
* zincati: add metrics collection and reporting
=> Release 0.0.2

src/identity/mod.rs
This updates the hardcoded stream label, as a temporary measure for
preview release.
Ref: https://github.com/coreos/zincati/issues/55
=> identity: update hardcoded stream

dist/polkit-1/rules.d/zincati.rules
Add a polkit rule to allow the `zincati` user to make `deploy` and
`finalize-deployment` calls to the D-Bus API exposed by rpm-ostree.
=> dist: add polkit rule for rpm-ostree

Cargo.lock, Cargo.toml, src/rpm_ostree/mod.rs
This improves input validation on input releases/nodes coming
from the Cincinnati server, with relevant tests too.
=> rpm-ostree: improve input validation

dist/config.d/10-auto-updates.toml, docs/usage/auto-updates.md, src/config/fragments.rs, src/config/inputs.rs, src/config/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs, tests/fixtures/00-config-sample.toml
This adds an `updates.enabled = <bool>` configuration entry to disable
auto-updates logic.
Closes: https://github.com/coreos/zincati/issues/62
=> update_agent: add a knob to disable auto-updates logic

src/identity/mod.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mod.rs, tests/fixtures/rpm-ostree-status.json
This removes the hardcoded stream value, introspecting it from booted
deployment metadata instead.
Closes: https://github.com/coreos/zincati/issues/55
=> identity: introspect updates stream

Cargo.lock, Cargo.toml
zincati 0.0.3:
* identity: introspect updates stream
* rpm_ostree/deploy: record metrics
* update_agent: add a knob to disable auto-updates logic
* rpm-ostree: improve input validation
* identity: introspect basearch
* dist: add polkit rule for rpm-ostree
* update-agent: observe state changes
* identity: update hardcoded stream
=> Release 0.0.3

src/cincinnati/client.rs, src/cincinnati/mod.rs
This instruments the cincinnati module, adding two metrics in order
to count total update checks and errors.
=> cincinnati/metrics: instrument update checks

docs/usage/metrics.md
This adds a user-doc page showing how to gather metrics from Zincati.
=> docs: show metrics usage

docs/usage/logging.md
This adds a new user-doc page showing how to tweak/increase log
verbosity via systemd drop-ins.
=> docs: show how to tweak verbosity

dist/systemd/system/zincati.service
This tweaks Zincati service unit in order to start a bit later in
the boot process.
In particular, we want to be scheduled after two other targets
have been reached:
* `network.target`: network is required to reach Cincinnati, so it
should start setting up before zincati starts.
* `boot-complete.target`: for remote coordination, releasing the
locked update-slot should happen only if the system is fully
operational after reboot.
=> dist/systemd: delay zincati boot order

src/cincinnati/mock_tests.rs, src/config/fragments.rs, src/config/inputs.rs, src/identity/mod.rs, src/main.rs, tests/fixtures/00-config-sample.toml
This drops the `throttle_permille` parameter, as it is not going
to be stabilized in its current form as part of the protocol.
=> cincinnati: drop throttle parameter

src/rpm_ostree/cli_finalize.rs
This records some metrics on 'rpm-ostree finalize-deployment' runs,
including total attempts and failures.
=> rpm_ostree/finalize: record metrics

.travis.yml, Cargo.lock, Cargo.toml, src/main.rs, src/rpm_ostree/cli_deploy.rs
This adds some testing mocks around `rpm-ostree deploy`, starting
with simple metrics checks. Failpoints in here can be later re-used
in order to test consumers.
=> rpm_ostree/deploy: add faulting tests for CLI calls 

Cargo.lock, Cargo.toml
* rpm_ostree/deploy: add faulting tests for CLI calls 
* update_agent: log relevant transaction events
* rpm_ostree/finalize: record metrics
* cincinnati: drop throttle parameter
* zincati: tweak logging
* dist/systemd: delay zincati boot order
* docs: show how to tweak verbosity
* docs: show metrics usage
* cincinnati/metrics: instrument update checks
* cargo: update dependencies
=> Release 0.0.4

Cargo.lock, Cargo.toml, dist/config.d/10-auto-updates.toml, dist/config.d/10-identity.toml, src/config/fragments.rs, src/config/inputs.rs, src/identity/mod.rs, tests/fixtures/00-config-sample.toml
This exposes an `identity.rollout_wariness = <float>` configuration
knob. It allows clients to pick their own constant wariness for
throttled rollout. Allowed values are within the range from `0.0`
(bold clients) to `1.0` (cautious clients), limits included.
Closes: https://github.com/coreos/zincati/issues/82
=> identity: allow setting rollout wariness

src/cincinnati/mod.rs, src/identity/mod.rs, src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mock_tests.rs, src/rpm_ostree/mod.rs, src/update_agent/mod.rs
This implements total ordering on releases, based on metadata
provided by the Cincinnati server.
In particular, from now on we require a metadata entry named
`org.fedoraproject.coreos.releases.age_index` which allows us
to compare the age (i.e. positional index) of releases as they
originally appear in the stream release index.
=> rpm_ostree: add release ordering based on age-index

src/identity/mod.rs
This implements logic to provide OS version to the Cincinnati server,
as an `os_version` client parameter.
Closes: https://github.com/coreos/zincati/issues/96
=> identity: provide OS version to Cincinnati

dist/systemd/system/zincati.service
Change the path to the installed binary from `/usr/bin/zincati` to
`/usr/libexec/zincati`. This is done because `zincati` is not
currently intended to be run directly by users.
When installing Zincati and running Zincati through this unit, the
binary placed by `cargo install` should be moved to this location
under `/usr/libexec`.
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/244
=> dist/systemd: change binary path to /usr/libexec

src/identity/mod.rs, src/rpm_ostree/mock_tests.rs
This adds back the OS checksum in Cincinnati client parameters,
which was dropped by mistake in https://github.com/coreos/zincati/pull/101.
=> identity: send OS checksum to Cincinnati

dist/systemd/system/zincati.service
...such as on a live system.  We can't perform updates in that case.
=> dist/systemd: don't start Zincati if booted as a live system

src/cincinnati/mod.rs, src/strategy/immediate.rs, src/strategy/mod.rs
This fixes several old-style trait object signatures, to avoid all
warnings like "trait objects without an explicit `dyn` are deprecated".
=> zincati: update trait object syntax

Cargo.lock, Cargo.toml
* github: add feature template
* zincati: improve logging and metrics
* identity: send OS checksum to Cincinnati
* identity: track rollout wariness in metrics
* dist/systemd: change binary path to /usr/libexec
* identity: provide OS version to Cincinnati
* rpm_ostree: add release ordering based on age-index
* docs: update LICENSE content from apache.org
* identity: allow setting rollout wariness
* cargo: update dependencies to latest versions
Ref: https://github.com/coreos/zincati/milestone/1?closed=1
=> Release 0.0.5

src/cincinnati/mock_tests.rs, src/cincinnati/mod.rs, src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mock_tests.rs, src/rpm_ostree/mod.rs, src/update_agent/actor.rs
This improves rpm-ostree and Cincinnati logic to detect releases
already deployed locally, and to exclude them from the update targets
while evaluating the update graph.
This effectively stops Zincati from misbehaving whenever the booted
deployment is not the default or the most recent one.
Closes: https://github.com/coreos/zincati/issues/111
=> rpm-ostree: do not update to already deployed releases

Cargo.lock, Cargo.toml, src/update_agent/actor.rs
This adds a small random amount of jitter (0% to 10%) to the refresh
loop period. It is meant to prevent multiple clients from converging
into a problematic stable state where all the (distributed) refresh
events are isochronous.
Closes: https://github.com/coreos/zincati/issues/139
=> update_agent: introduce some jitter in the refresh loop

Cargo.lock, Cargo.toml, dist/config.d/30-updates-strategy.toml, src/config/fragments.rs, src/config/inputs.rs, src/config/mod.rs, src/fleet_lock/mock_tests.rs, src/fleet_lock/mod.rs, src/main.rs, src/strategy/fleet_lock.rs, src/strategy/immediate.rs, src/strategy/mod.rs, tests/fixtures/00-config-sample.toml
This adds configuration and logic for a `fleet_lock` update strategy,
which allows cluster-wide reboot coordination.
Protocol: https://github.com/coreos/airlock/pull/1
Docs: https://github.com/coreos/zincati/pull/134
Closes: https://github.com/coreos/zincati/issues/37
=> strategy: add FleetLock cluster-wide reboot coordination

docs/usage/auto-updates.md, docs/usage/updates-strategy.md
This adds documentation for updates strategies. In particular this
explains how the lock-based strategy works, and how to configure it.
=> docs: explain lock-based updates strategy

src/identity/mod.rs
This renames the OS version label to be less generic, making its
usage more meaningful at query-time.
=> identity: rename OS version metrics

README.md, docs/usage/configuration.md
This adds documentation explaining how Zincati configuration works.
It shows directories sorting and dropins overrides.
=> docs: add configuration documentation

src/cincinnati/client.rs, src/cincinnati/mod.rs, src/fleet_lock/mod.rs, src/strategy/fleet_lock.rs
This uniforms all FleetLock-related logic to use a module-specific
error type. The intent is to make sure each failure can be recorded
with machine-friendly and human-friendly identifiers.
For server errors, it tracks the status code too.
It also augments error metrics with the machine-friendly
kind and api endpoint.
=> strategy/fleet_lock: uniform and instrument errors

Cargo.lock, Cargo.toml
Changes:
* cincinnati: evaluate dead-end status for booted OS
* strategy/fleet_lock: uniform and instrument errors
* cincinnati: uniform and instrument error kinds
* docs: add configuration documentation
* fleet_lock: update protocol parameters
* identity: rename OS version metrics
* docs: visualize updates finalization
* docs: explain lock-based updates strategy
* strategy: add FleetLock cluster-wide reboot coordination
* rpm_ostree/deploy: do not error on exit code 77
* update_agent: introduce some jitter in the refresh loop
* rpm-ostree: do not update to already deployed releases
* identity: expose OS version metrics
* docs: explain phased rollouts and client wariness
Tracker: https://github.com/coreos/zincati/milestone/3?closed=1
=> Release 0.0.6

src/rpm_ostree/cli_deploy.rs
This reverts commit f2a5a486021b2e1440b84a7975d89f88446a2787.
The workaround is not anymore necessary after rpm-ostree v2019.6.
Closes: https://github.com/coreos/zincati/issues/143
=> Revert "rpm_ostree/deploy: do not error on exit code 77"

dist/config.d/10-auto-updates.toml, docs/usage/auto-updates.md, src/cincinnati/mock_tests.rs, src/cincinnati/mod.rs, src/config/fragments.rs, src/config/inputs.rs, src/config/mod.rs, src/rpm_ostree/actor.rs, src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/mock_tests.rs, src/strategy/fleet_lock.rs, src/update_agent/actor.rs, src/update_agent/mod.rs, tests/fixtures/00-config-sample.toml
This denies downgrades by default, but introduces a configuration
boolean `updates.allow_downgrade` (default: `false`) to disable
such logic for setups where deploying downgrades is fine.
Zincati only performs best-effort filtering based on the age-index
from the Cincinnati server, while the final enforcement is performed
by rpm-ostree based on real timestamps.
Closes: https://github.com/coreos/zincati/issues/87
=> updates: block downgrades, expose opt-in config

.travis.yml
Bumping to 1.38 in order to cope with dependency updates.
=> ci: bump minimum supported Rust version to 1.38

.github/ISSUE_TEMPLATE/release-checklist.md
This adds a bug template for GitHub detailing all steps that are
performed in the release process, as a checklist.
=> github: add release-checklist template

Cargo.lock, Cargo.toml
Changes:
* updates: block downgrades, expose opt-in config
* Revert "rpm_ostree/deploy: do not error on exit code 77"
* ci: bump minimum supported Rust version to 1.38
* github: add release-checklist template
Tracker: https://github.com/coreos/zincati/milestone/4?closed=1
=> Release 0.0.7

docs/usage/metrics.md
Fedora CoreOS replaced `nmap-ncat` with `socat`, so this updates the
shell example to be directly usable there.
Ref: https://github.com/coreos/fedora-coreos-config/pull/218
=> docs: update metrics example

src/update_agent/actor.rs, src/update_agent/mod.rs
This tweaks refresh logic in order to make the refresh interval
specific to each state. It will allow exposing knobs to tweak
refresh delays for some states, later on.
Ref: https://github.com/coreos/zincati/issues/203
=> update_agent: make intervals state specific

src/cincinnati/client.rs, src/fleet_lock/mod.rs
This adds support to detect system proxy from environment variables,
using it for all HTTP clients (i.e. cincinnati and fleet_lock).
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/379
=> zincati: use system proxy in HTTP clients

.travis.yml, src/cincinnati/client.rs, src/fleet_lock/mod.rs
This fixes all existing warnings and adds a `clippy` job to travis.
=> ci: add a clippy run to travis

dist/config.d/10-agent.toml, src/config/fragments.rs, src/config/inputs.rs, src/config/mod.rs, src/update_agent/mod.rs, tests/fixtures/00-config-sample.toml
This adds support for a new config section `agent.timing` to configure
timing-related settings on the agent.
It currently has a single knob `steady_interval_secs` to tweak the refresh
period while in steady state.
Closes: https://github.com/coreos/zincati/issues/203
=> config: add agent timing knobs

Cargo.toml
This fixes manifest metadata for latest `cargo-release`.
=> cargo: fix release metadata

Cargo.lock, Cargo.toml
Changes:
* cargo: fix release metadata
* config: add agent timing knobs
* ci: add a clippy run to travis
* zincati: use system proxy in HTTP clients
* update_agent: make intervals state specific
* docs: update metrics example
* docs: minor fixes to release checklist
Tracker: https://github.com/coreos/zincati/milestone/5
=> Release 0.0.8

src/cincinnati/client.rs, src/fleet_lock/mod.rs
This adds a total completion timeout of 30 minutes to all HTTP
requests for the Cincinnati and FleetLock clients.
=> zincati: add completion timeout to HTTP requests

.travis.yml, Cargo.lock, Cargo.toml, src/cincinnati/client.rs, src/cincinnati/mock_tests.rs, src/cincinnati/mod.rs, src/fleet_lock/mock_tests.rs, src/fleet_lock/mod.rs, src/metrics/mod.rs, src/rpm_ostree/mock_tests.rs, src/strategy/fleet_lock.rs, src/strategy/immediate.rs, src/strategy/mod.rs, src/update_agent/actor.rs
This reworks the whole codebase to use new-style `Futures` from
Rust stdlib, and futures-0.3 combinators.
In turn, this allows updating all other queued dependency versions
(tokio, reqwest, and actix).
Closes: https://github.com/coreos/zincati/issues/223
=> zincati: rework to use std::future

Cargo.lock, Cargo.toml
This drops strict requirements on micro versions in order to make
packaging efforts more relaxed.
=> cargo: relax dependencies micro versions

src/update_agent/actor.rs, src/update_agent/mod.rs
This splits the "reported steady" and "checked, but no updates
available" states, making it easier to track and report upgrade
progress.
Closes: https://github.com/coreos/zincati/issues/229
=> update-agent: rework steady/polling state

dist/tmpfiles.d/zincati.conf, docs/usage/metrics.md, src/metrics/mod.rs
This stabilize the metrics endpoint under its new public path,
`/run/zincati/public/metrics.promsock`.
Previous private path is kept as a symlink for compatibility.
Closes: https://github.com/coreos/zincati/issues/74
=> metrics: stabilize metrics endpoint

Cargo.lock, Cargo.toml
Changes:
* zincati: rework to use std::future
* zincati: add completion timeout to HTTP requests
* metrics: stabilize metrics endpoint
* update-agent: rework steady/polling state
* docs: add state-machine diagram
* cargo: relax dependencies micro versions
* cargo: update all dependencies
Tracker: https://github.com/coreos/zincati/milestone/6
=> Release 0.0.9

.cci.jenkinsfile, Makefile
Add a build & kola test to the repo. Notably, we also run the upgrade
tests since zincati is a big part of this.
=> ci: hook up to CoreOS CI

dist/config.d/50-fedora-coreos-cincinnati.toml
This updates the default FCOS Cincinnati endpoint, switching from
staging infrastructure to production one.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/347
=> config: update FCOS Cincinnati endpoint (prod)

docs/contributing.md, docs/development/os-metadata.md
This records all the details and OS metadata which are required by
Zincati in order to properly derive its own agent identity.
Fixes: https://github.com/coreos/zincati/issues/271
=> docs/devel: document required metadata for introspection

Cargo.lock, Cargo.toml
Changes:
* update-agent: react to persistent deploy failure
* docs/devel: document required metadata for introspection
* strategy: add logic for weekly maintenance windows
Tracker: https://github.com/coreos/zincati/milestone/8
=> Release 0.0.11

docs/development/cincinnati/protocol.md, docs/development/cincinnati/response.json
This adds dev-docs describing how the Cincinati protocol works and
how it is used by Fedora CoreOS.
This covers both client-side and server-side additional constraints
specific to FCOS.
=> docs/dev: describe the Cincinnati protocol used by Fedora CoreOS

src/strategy/mod.rs, src/strategy/periodic.rs, src/weekly/mod.rs
This adds two info metrics covering the configured update strategy:
* `zincati_updates_strategy_mode{strategy="<MODE>"}`
* `zincati_updates_strategy_periodic_schedule_length_minutes`
The first is an info metrics covering the strategy mode in all cases;
the second only applies to the "periodic" strategy and tracks the
schedule length.
Ref: https://github.com/coreos/zincati/issues/305
=> strategy: add metrics to track updates strategy configuration

README.md, docs/usage/auto-updates.md
This updates a few lists in docs with relevant items pointing to the
newly introduced `periodic` strategy documentation.
=> docs: add more references to periodic strategy section

src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs, src/update_agent/actor.rs, tests/fixtures/rpm-ostree-staged.json
This augments rpm-ostree status querying logic in order to detected
staged-but-not-finalized deployments, i.e. those that haven't really
been persisted locally in the past.
Zincati uses this new logic in order to distinguish between previous
deployments (e.g. in case of rollbacks) and temporarily staged ones
(e.g. in case of manual interventions or half-applied updates). The
latter ones can be considered as future update targets, while the
former ones should not.
Fixes: https://github.com/coreos/zincati/issues/293
=> rpm-ostree/status: detect and handle staged deployments

.gitignore, contrib/monitoring-mixins/README.md, contrib/monitoring-mixins/dashboards/dashboards.libsonnet, contrib/monitoring-mixins/jsonnetfile.json, contrib/monitoring-mixins/mixin.libsonnet
This adds initial monitoring mixins, in order to ease consuming
Zincati metrics on a fleet of Fedora CoreOS nodes. Currently this
only covers Grafana dashboards.
See https://monitoring.mixins.dev/ for general details on
monitoring mixins.
---
Dashboard rendered with metrics from two canary machines ([1](https://fcos-metrics-21.lucabruno.net/bridge?selector=zincati), [2](https://fcos-metrics-31.lucabruno.net/bridge?selector=zincati)):
=> contrib: add monitoring mixins

src/cincinnati/client.rs, src/cincinnati/mod.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mock_tests.rs, src/strategy/fleet_lock.rs, src/strategy/immediate.rs, src/strategy/mod.rs, src/strategy/periodic.rs, src/update_agent/actor.rs
Cleanup checklist:
Closes: https://github.com/coreos/zincati/issues/35
Signed-off-by: Allen Bai <abai@redhat.com>
=> strategy: cleanup unused logic

src/strategy/fleet_lock.rs, src/strategy/immediate.rs, src/strategy/mod.rs, src/strategy/periodic.rs
This attaches mode-label constants and uses them for
configuration parsing and when forwarding to metrics labels.
It helps making sure that the `Default` implementation has a
uniform behavior and a non-empty value in metrics labels.
=> strategy: uniformly use config labels

Cargo.lock, Cargo.toml
Changes:
* strategy: uniformly use config labels
* strategy: cleanup unused logic
* contrib: add monitoring mixins
* rpm-ostree/status: detect and handle staged deployments
* docs: add more references to periodic strategy section
* strategy: add metrics to track updates strategy configuration
* ci: update travis toolchains
* docs/dev: describe the Cincinnati protocol used by Fedora CoreOS
* docs/update-strategy: make airlock a link
* github: create Dependabot config file
* docs/images: add a sequence diagram for locked reboots
* docs/dev: add some details on periodic strategy design
Tracker: https://github.com/coreos/zincati/milestone/9?closed=1
=> Release 0.0.12

src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/cli_finalize.rs, src/rpm_ostree/cli_status.rs
When calling the rpm-ostree cli set the RPMOSTREE_CLIENT_ID environment
variable to 'zincati' so that rpm-ostree knows which client is calling
it.
Fixes #131
Signed-off-by: Clement Verna <cverna@tutanota.com>
=> rpm-ostree: set RPMOSTREE_CLIENT_ID env variable

src/identity/mod.rs
This commit extends the OS_INFO prometheus metric to add the
basearch, stream and platform information.
The final metrics looks like :
```
zincati_identity_os_info{basearch="x86_64",os_version="32.20200629.3.0",platform="qemu",stream="stable"} 1
```
Fixes #120
Signed-off-by: Clement Verna <cverna@tutanota.com>
=> identity: add more details to the OS_INFO metrics

.travis.yml, src/weekly/mod.rs
This updates rustfmt and clippy to latest stable toolchain, for
Travis jobs.
=> ci: bump toolchain for lints on Travis

Cargo.toml
This adds the homepage field to Cargo manifest, pointing it to the
auto-built pages.
Ref: https://coreos.github.io/zincati
=> cargo: add homepage

docs/contributing.md
Unfortunately this make the link point to an "empty" page when viewing directly on GitHub. This could be improved by adding context in the development page.
Preview: https://travier.github.io/zincati/contributing/
=> docs: Fix development link in contributing doc

docs/development/fleetlock/protocol.md, docs/usage/updates-strategy.md
This adds a complete description of the FleetLock protocol used by
Zincati for cluster-wide coordinated reboots.
=> docs/dev: add FleetLock protocol specs

Cargo.lock, Cargo.toml
Changes:
* identity: add more details to the OS_INFO metrics
* rpm-ostree: set RPMOSTREE_CLIENT_ID env variable
* metrics: expose process start timestamp
* github: release checklist cleanups
* cargo: update prometheus to latest version
* cargo: add homepage
* ci: bump toolchain for lints on Travis
* docs/dev: add FleetLock protocol specs
* docs: Fix development link in contributing doc
* docs: Add contributing & simplify Jekyll front matter
* docs: misc cleanups
* docs: add initial scaffolding for GitHub Pages
Tracker: https://github.com/coreos/zincati/milestone/10?closed=1
=> Release 0.0.13

src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/cli_finalize.rs, src/rpm_ostree/cli_status.rs
This fixes error context on rpm-ostree failed runs in order to
avoid duplicating the underlying error cause. Failure chain already
includes the root cause as the next element, thus there is no need
to also embed it in the parent context.
=> rpm-ostree: avoid duplicating error causes

Cargo.lock, Cargo.toml, src/update_agent/actor.rs
This updates to actix-0.10 and adapts the existing code to the new API.
=> cargo: update actix to latest version

docs/usage/logging.md
This clarifies a few existing details related to log levels and
introduces a section covering `journalctl` and how to inspect logs
on a live system.
=> docs/usage: expand logging page

src/rpm_ostree/cli_status.rs, tests/fixtures/rpm-ostree-status.json
A great thing about serde (as well as structopt) is that
you can achieve a high level of
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
Use `rename_all` here because that's the naming standard,
and if we start parsing other values then we don't
need to specify a rename attribute for each one.
=> rpm_ostree: Use rename_all = kebab-case

Cargo.toml
This removes all carets (^) from dependencies, resulting in
semver entries which are semantically equivalent from cargo
point of view.
This repository is starting to accumulate stale dependencies, as
dependabot is having troubles when trying to update them. The
issue seems related to `^` requirements confusing the bot.
Ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio
=> cargo: remove carets from semver requirements

Cargo.lock, Cargo.toml
`url_serde` is no longer required for URL serialization.
This directly enables the "serde" feature on `url` instead.
Ref: https://github.com/servo/rust-url/blob/master/UPGRADING.md#upgrading-from-url-1x-to-21
=> cargo: switch to latest url version for serde support

.travis.yml
This updates the linting toolchain in Travis to latest stable (1.47.0).
=> ci: bump linting toolchain in Travis

Cargo.lock, Cargo.toml, Makefile, dist/polkit-1/actions/org.coreos.zincati.deadend.policy, dist/polkit-1/rules.d/zincati.rules, src/cincinnati/mod.rs, src/cli/mod.rs, src/main.rs
After checking whether the current Cincinnati node is a dead-end or
not, write out a new MOTD file at `/run/motd.d/deadend.motd`
reflecting the dead-end status. If the current release is a deadend,
a message is printed in the MOTD containing the reason for the
release being a deadend. An info message is also logged. If not a
dead-end release a blank MOTD is written and no message is logged.
To make the final write atomic, a tempfile is written within the
`/run/motd.d/` directory, and renamed to the location
of the complete MOTD to display.
In this case, "pkexec" utility is used to allow Zincati (which runs as
the `zincati` sysuser) to modify root-owned `/run/motd.d/` in order to
write dead-end release information into a MOTD file, and the polkit rule
will ensure that that utility runs …
=> cincinnati: expose dead-end release information via MOTD

src/cli/agent.rs, src/cli/deadend.rs, src/cli/mod.rs, src/main.rs
This splits and moves subcommands logic out of main, into their own
`cli` modules.
=> cli: split subcommands logic out of main

docs/development/fleetlock/protocol.md, src/fleet_lock/mod.rs
- Fix an error in fleet lock request example (group named `default` in the example request, but named `workers` in the paragraph before)
- Update to new fleet lock spec location
=> docs/dev: fix fleetlock documentation

src/cli/deadend.rs
This improves error messages by adding the faulty filepath and
avoiding duplicating the underlying error kind.
It also massages the surrounding code introducing constants for
paths and if-let bindings.
=> cli/deadend: rework errors with relevant context

dist/systemd/system/zincati.service
Otherwise, it's possible that the reboot we trigger will have
`ConditionFirstBoot=true` services run again because systemd didn't have
time to write `/etc/machine-id`.
Symmetrically, all services (ours or user-provided ones) which use
`ConditionFirstBoot=true` must learn to use
`Before=first-boot-complete.target` (which is just before
`systemd-machine-id-commit.service`).
This is more of a theoretical issue than anything given how long Zincati
and rpm-ostree realistically take to trigger, download, and stage an
update. OTOH, we can't be 100% sure no user-provided service will ever
hit this race.
For more details, see discussions in:
https://github.com/systemd/systemd/issues/4511
=> zincati.service: run after systemd-machine-id-commit.service

.github/ISSUE_TEMPLATE/release-checklist.md
This will update the release instructions to clarify the step while publishing a release and the `UPSTREAM_REMOTE` keyword.
=> github: update the release instructions

docs/development/agent-actor-system.md, docs/development/os-metadata.md, docs/development/update-strategy-periodic.md
This adds a development page describing the internal structure of
the `agent` long-running service.
In particular, this introduces the underlying actor model and
provides an overview of the existing actors.
=> docs/dev: describe agent design and actor system

dist/polkit-1/actions/org.coreos.zincati.deadend.policy, src/cincinnati/mod.rs, src/cli/deadend.rs, src/cli/mod.rs
This reworks the subcommand for deadend MOTD handling into two
explicit verbs:
* `zincati deadend-motd set --reason <REASON>`
* `zincati deadend-motd unset`
It also adds tests covering flags parsing for the subcommand.
=> cli/deadend: split explicit set/unset verbs and logic

Cargo.lock, Cargo.toml
Changes:
* cli/deadend: split explicit set/unset verbs and logic
* docs/dev: describe agent design and actor system
* github: update the release instructions
* zincati.service: run after systemd-machine-id-commit.service
* docs/dev: add graph for actors and interactions
* cli/deadend: rework errors with relevant context
* docs/dev: fix fleetlock documentation
* cincinnati: swap order of dead-end refreshing logic
* cli: split subcommands logic out of main
* cincinnati: expose dead-end release information via MOTD
* ci: bump linting toolchain in Travis
* cargo: switch to latest url version for serde support
* cargo: remove carets from semver requirements
* rpm_ostree: Use rename_all = kebab-case
* docs/usage: expand logging page
* cargo: update actix to latest version
* main: pretty-print …
=> Release 0.0.14

.github/workflows/rust.yml
This refines the triggering conditions for GH actions in order
to avoid running duplicated jobs on local branches.
=> workflows/rust: avoid duplicated runs

.github/workflows/containers.yml, Makefile, contrib/Dockerfile.dev
This adds a Dockerfile for a container development image, and wires
it to GitHub workflows.
Additionally, the workflow produces a rootfs-override artifact (with
full-debug binary) that can be directly plugged into coreos-assembler
overrides.
=> contrib: add dev container flow

src/strategy/mod.rs, src/strategy/periodic.rs, src/update_agent/actor.rs, src/weekly/mod.rs
This logs an info message on startup, in order to record some
details related to the update strategy in use.
In particular, this is helpful when using the 'periodic' strategy
as it shows the remaining time till the next update window.
Closes: https://github.com/coreos/zincati/issues/305
=> strategy: record details on startup

.github/workflows/rust.yml
This updates the linting toolchain to latest stable (1.48.0).
=> workflows: update linting toolchain to latest stable

docs/development/agent-actor-system.md, docs/development/fleetlock/protocol.md, docs/development/os-metadata.md, docs/development/quickstart.md, docs/development/update-strategy-periodic.md
This adds a quickstart guide for developers, showing how to build/test
Zincati and how to embed it into an OS image via coreos-assembler.
Closes: https://github.com/coreos/zincati/issues/353
=> docs/dev: add a quickstart guide

src/cli/agent.rs, src/config/mod.rs, src/strategy/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
This moves metrics initialization early on, for those values that
are set from configuration settings and are already known at
startup.
Closes: https://github.com/coreos/zincati/issues/420
=> config: set metrics values earlier

Cargo.lock, Cargo.toml, docs/usage/agent-identity.md, src/identity/mod.rs
This adds a validity check for the group label, making sure that
user-customized settings (if any) are valid and can be used in
Cincinnati and FleetLock requests.
Closes: https://github.com/coreos/zincati/issues/351
=> identity: validate group settings

.github/ISSUE_TEMPLATE/release-checklist.md
This tweaks release-checklist steps, adding instructions on how
to generate and attach the vendor tarball to each release.
=> github/release-checklist: generate vendor tarball too

Cargo.lock, Cargo.toml
Changes:
* github/release-checklist: generate vendor tarball too
* update-agent: expose current state via sd_notify
Tracker: https://github.com/coreos/zincati/milestone/13?closed=1
=> Release 0.0.16

docs/usage/metrics.md
See: https://travier.github.io/zincati/usage/metrics/ vs https://coreos.github.io/zincati/usage/metrics/
=> docs/usage/metrics: Minor link fix for Jekyll pages

src/cincinnati/mod.rs, src/update_agent/actor.rs
Zincati ignores possible update targets that have previously been
deployed. Log this explicitly so there's no confusion when e.g. users
do a rollback.
Closes: https://github.com/coreos/zincati/issues/338
=> cincinnati: record ignored update targets in logs and metrics

src/update_agent/actor.rs
This fixes status updating logic, in order to display the timestamp
of the last check (instead of the last state change).
=> update_agent: fix timestamp in status updates

src/update_agent/actor.rs
Generally, state changes trigger immediate ticks; make an exception
for the case where we're transitioning from ReportedSteady to
NoNewUpdates. This will prevent Zincati from performing the first
two polls for updates consecutively with no delay in between.
=> update-agent: add some delay after first Cincinnati check

dist/systemd/system/zincati.service, src/update_agent/actor.rs, src/update_agent/mod.rs
Broadcast to users before reboot by writing a message to their
ttys.
Closes: #114
=> agent: Broadcast message to logged in users before rebooting

Cargo.lock, Cargo.toml
Changes:
- update-agent: 
- log finalized deployments at start up
- broadcast warning immediately before update finalizations
- add some delay after first Cincinnati check
- cincinnati: 
- add metric for number of ignored update targets
- rpm-ostree: 
- cache status to minimize binary invocations
- expose status-related metrics
Tracker: https://github.com/coreos/zincati/milestone/15?closed=1
=> Release 0.0.18

src/rpm_ostree/actor.rs, src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/mod.rs, src/update_agent/actor.rs
Following https://github.com/coreos/rpm-ostree/pull/2459, rpm-ostree
now has a mechanism for third-party update drivers to register as
its update driver.
Register Zincati as the update driver in the "initialization" stage.
=> Register as update driver for rpm-ostree

src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs
Prep for updating to use the rpm-ostree client bindings; I hit
the problem that the current struct doesn't implement `Clone`.
I could have easily added that, but conceptually it's a bit wrong
to have our cache gather some data, immediately do a full copy,
then discard the original.
I tried fighting the borrow checker here to have the function
return a reference; doesn't seem possible.  In the end with this
type of cache I think it's just cleaner to use reference counting;
there's no concerns about circular references etc.
=> rpmostree: Use Rc for status caching

Cargo.lock, Cargo.toml, src/cli/agent.rs, src/cli/deadend.rs, src/cli/mod.rs
Error out if not run by the `zincati` user for the `agent` and
`deadend-motd` subcommands, since the update agent should only be
running as the `zincati` user and `deadend-motd` should not be used
externally.
The binary is currently already placed in `/usr/libexec` in Fedora, but doing
this for extra safety and clarity.
Closes: https://github.com/coreos/zincati/issues/95
Example output:
```
$ /usr/libexec/zincati agent
[WARN ] zincati binary should not be run directly
[ERROR] critical error: update agent not running as `zincati` user
```
```
$ /usr/libexec/zincati deadend-motd unset
[WARN ] zincati binary should not be run directly
[ERROR] critical error: deadend-motd subcommand must be run by `zincati` user
```
=> cli: Check if run as `zincati` user

src/cli/agent.rs, src/cli/deadend.rs, src/cli/mod.rs
Add a `user` argument to `ensure_user()` so we can ensure different
users flexibly. Specifically, for the `agent` subcommand, we want
to ensure that only the `zincati` user can run it. But for the
`deadend-motd` subcommand, we want to make sure that it is run by
`root`, otherwise, the creation of the MOTD will fail anyway.
Note that `deadend-motd` is still only meant to be called internally by
the `agent` process started by `zincati.service` as the `zincati`
user; but in order to write the MOTD, the `agent` process `pkexec`s
as the `root` user before calling the `deadend-motd` subcommand. This
is the reason that we do not check that user is `zincati`, but `root`,
instead.
Addresses: https://github.com/coreos/zincati/pull/495#discussion_r593107325
Closes …
=> cli: make check for user more flexible

.github/ISSUE_TEMPLATE/release-checklist.md
Remove extra and premature "publish the release" in the "Publish the release"
section.
=> release-checklist: remove extraneous words

Cargo.lock, Cargo.toml
Changes:
- update-agent:
- register as update driver for rpm-ostree
- don't consider transition into own state a "state change"
- delay reboot if users logged in
- add update finalization postponement metrics
- cli: 
- check if run as `zincati` user
- make check for user more flexible
- rpm-ostree: 
- Use Rc for status caching
Tracker: https://github.com/coreos/zincati/milestone/16
=> Release 0.0.19

docs/development/testing.md, tests/kola/server/config.fcc, tests/kola/server/test-deadend-release.sh
tests/kola: add dead-end MOTD kola test
Create a new kola test directory that contains a Fedora CoreOS
config that sets up an HTTP server and configure Zincati to use
it as its Cincinnati server.
Include a test to check that Zincati correctly detects a deadend
release and successfully generates a MOTD.
docs/development: add testing docs
=> tests/kola: add dead-end MOTD kola test

.github/workflows/containers.yml
I think we should try to have a common workflow across CoreOS
projects, so use the new upstream buildroot.
=> ci: Use fcos buildroot

contrib/Dockerfile.dev, docs/development/quickstart.md
We can just use for development the same image that CI in CoreOS projects use.
=> doc/quickstart: use FCOS buildroot image

Cargo.lock, Cargo.toml, src/cincinnati/client.rs, src/cincinnati/mod.rs, src/cli/agent.rs, src/cli/deadend.rs, src/cli/ex.rs, src/cli/mod.rs, src/config/inputs.rs, src/config/mod.rs, src/dbus/mod.rs, src/fleet_lock/mod.rs, src/identity/mod.rs, src/identity/platform.rs, src/main.rs, src/metrics/mod.rs, src/rpm_ostree/actor.rs, src/rpm_ostree/cli_deploy.rs, src/rpm_ostree/cli_finalize.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mod.rs, src/strategy/fleet_lock.rs, src/strategy/immediate.rs, src/strategy/mod.rs, src/strategy/periodic.rs, src/update_agent/actor.rs, src/update_agent/mod.rs, src/weekly/mod.rs, src/weekly/utils.rs
The `failure` library is now deprecated, use `anyhow` instead.
Same motivation as https://github.com/coreos/bootupd/pull/163.
Effectively what we're doing here is creating a human-readable subset
of the stack trace. This is nicer than having the calling functions
add `with_context()` because it's more verbose (gets duplicative at
each call site), easy to forget, etc.
While we're at it, add some `fn-error-context`-style contexts to
functions whose callers forgot to or didn't add context.
=> Clean up error handling

Cargo.lock, Cargo.toml, docs/development/update-strategy-periodic.md, docs/usage/updates-strategy.md, src/config/fragments.rs, src/config/inputs.rs, src/strategy/fleet_lock.rs, src/strategy/mod.rs, src/strategy/periodic.rs, src/weekly/mod.rs, src/weekly/utils.rs, tests/fixtures/00-config-sample.toml, tests/fixtures/30-periodic-sample-non-utc.toml, tests/fixtures/31-periodic-sample-non-utc.toml
Support configuring reboot windows defined by a user-specified time zone, instead of only UTC.
Include a single `time_zone` field (that defaults to UTC if not
specified) in the `periodic` strategy's configuration. Whenever we
need to check whether we're currently in an allowed reboot window,
we convert the current naive time to the naive time under the
specified time zone, and check whether we are currently in a reboot
window.
Under this implementation, we keep invariant clock time for reboots,
but do NOT keep invariant reboot window length; thus, in some cases,
reboot windows can be lengthened, shortened, or skipped entirely.
=> strategy/periodic: support configuring a time zone for reboot windows

Cargo.lock, Cargo.toml
Changes:
* strategy/periodic: support configuring a time zone for reboot windows
* src: clean up error handling
* agent: add new actor for D-Bus server interface
* cargo: bump tokio, actix, reqwest
* doc/quickstart: use FCOS buildroot image
* docs: fix "Edit this page on GitHub" links
* tests/kola: add dead-end MOTD kola test
* ci: adapt to new buildroot image
* ci: bump MSRV toolchain
* ci: bump linting toolchain
* ci: use fcos buildroot
Tracker: https://github.com/coreos/zincati/milestone/17
=> Release 0.0.20

src/update_agent/actor.rs
This logs the result of a deploy attempt, which is currently visible
as service status only.
=> update_agent: log deploy attempt outcome

docs/usage/updates-strategy.md
:warning: isn't rendered on GitHub Pages.
=> docs/usage/updates-strategy: use real emoji

Cargo.toml, src/cli/agent.rs, src/main.rs, src/update_agent/actor.rs, src/utils.rs, tests/kola/misc/test-status.sh
Currently, when we stop zincati.service, the systemd StatusText
remains as whatever it was before it was stopped. This is
somewhat misleading when the StatusText is shown in e.g.
`rpm-ostree status`.
=> main: update systemd StatusText on SIGTERM

src/update_agent/mod.rs
Reword message broadcasted to users when reboots are delayed due
to active interactive user sessions to emphasize that logging out
active sessions will allow Zincat to continue the auto-update
process.
=> update_agent: reword reboot delay broadcast mesage

Cargo.toml
This sets the new `sign-tag` metadata field which has been recently
by cargo-release.
=> cargo/release: set sign-tag property

src/rpm_ostree/actor.rs
This should help us determine when and whether calls to the
rpm-ostree CLI returns; this, together with
https://github.com/coreos/zincati/pull/543, should help us narrow
down whether the `update_agent` actor's apparent freeze during a
https://github.com/coreos/fedora-coreos-tracker/issues/756 test
flake is due to a non-returning rpm-ostree CLI or communication
issues between the `update_agent` actor and the `rpm_ostree` actor.
=> rpm_ostree/actor: add traces when CLI returns

Cargo.lock, Cargo.toml
Changes:
- docs/usage/updates-strategy: use real emoji
- update_agent: fix logic around reboot delays
- agent: clear systemd StatusText on SIGTERM
- update_agent: reword reboot delay broadcast mesage
- rpm_ostree/actor: add traces when CLI returns
- cargo: development version bump
- update_agent: log deploy attempt outcome
- cargo/release: set sign-tag property
Tracker: https://github.com/coreos/zincati/milestone/18
=> Release 0.0.21

dist/dbus-1/system.d/org.coreos.zincati.conf
This tweaks dbus configuration, fixing some mistakes in the ACLs.
It gets rid of the following dbus-broker warning:
> Conflicting attributes in /usr/share/dbus-1/system.d/org.coreos.zincati.conf +14
=> dist: fix dbus configuration

src/update_agent/mod.rs
There is no need to tick every 5 minutes once Zincati has reached
its end state (accessible either due to disablement via config or
waiting for rpm-ostree's finalization and reboot). Slow down to
three hours.
Closes https://github.com/coreos/zincati/issues/553.
=> update_agent: slow down end state tick cadence

.github/workflows/rust.yml, src/rpm_ostree/mod.rs, src/weekly/mod.rs
Fedora 34 (the base of FCOS in all release streams) is already on
1.53; bump MSRV to this, as well, since `zvariant` wants this.
Also bump the lints toolchain to the latest Rust version.
=> workflows: bump MSRV and lints toolchain

Cargo.lock, Cargo.toml
Changes:
* lockfile: general refresh, update all openssl crates
* Add more metrics around finalization attempts
* workflows: bump MSRV and lints toolchain
* update_agent: promote some log messages to INFO level
* update_agent: slow down end state tick cadence
* dist: fix dbus configuration
=> Release 0.0.22

src/rpm_ostree/cli_deploy.rs
Do not send a reply to the `update_agent` actor until the
`rpm_ostree` actor has successfully registered as driver. This
effectively blocks Zincati initialization on driver registration.
We consider failures to register as driver as transient failures,
so the `rpm_ostree` actor will keep retrying forever.
=> rpm_ostree/deploy: block on driver registration

src/cincinnati/mod.rs, src/identity/mod.rs, src/update_agent/actor.rs, src/update_agent/mod.rs
We would like to put update agent state behind a RwLock so ticks
can be handled sequentially while allowing messages to the
`update_agent` actor to be handled concurrently, in general.
Closes: https://github.com/coreos/zincati/issues/569
=> update_agent: put state behind RwLock

src/rpm_ostree/actor.rs, src/rpm_ostree/cli_deploy.rs, src/update_agent/actor.rs
Previously, the `tick_` functions returned a `Result`, but only two
of these functions would ever return the `Err` variant. Even in the
case where the returned `Result` was of the `Err` variant, the caller
does not really do anything with it.
Since we already do a good amount of error logging in the inner
functions, refactor the `tick_` functions to return `()` instead.
For helpers that return a `Result`, move error logging to the caller
functions.
Refactor `register_driver` to return `()`, because errors shouldn't
be returned since https://github.com/coreos/zincati/pull/599.
Use `anyhow::Result`.
Refactor `tick_finalize_update` to return early to avoid deeply nested
if-else statements.
=> update_agent: remove unused `Result`s

src/update_agent/actor.rs, src/update_agent/mod.rs
Since our actors are on the Actix system arbiter, which is single-
threaded, there is actually no need to use `Arc`. `Rc` should suffice
here.
=> update_agent: put state behind `Rc` instead of `Arc`

src/update_agent/actor.rs, src/update_agent/mod.rs
The previous incorrect usage of `RefCell` allowed for panics at runtime
if there were consumers.
`Cell` should be sufficient here, since the data that we are storing
is a simple timestamp (easily `Copy`-able). We do not need to use an atomic type because the
update_agent actor runs on a single thread on the SystemArbiter.
Ref: https://github.com/coreos/zincati/pull/614#discussion_r679747046
=> update_agent: use `Cell` for `state_changed` field

Cargo.lock, Cargo.toml
Changes:
- workflows: limit permissions to reading repo contents
- rpm_ostree/deploy: block on driver registration
- docs/images: update actor graph with D-Bus actor
- update_agent: put agent state behind a RwLock
- update_agent: remove unused `Result`s
- update_agent: misc cleanup
- update_agent: put state behind `Rc` instead of `Arc`
- update_agent: split state_changed out of UpdateAgentInfo
- update_agent: use `Cell` for `state_changed` field
- dist/config.d/*.toml: Add missing EOL
=> Release 0.0.23

src/update_agent/mod.rs
Keep all lines to 80 characters.
=> update_agent: improve linewrapping of logout warning

src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs, src/update_agent/actor.rs, tests/kola/server/test-stream.sh
This tweaks the staging and introspection logic in order to be more
resilient to failures, and to handle temporary errors in a graceful way.
In particular, the update agent is now more conservative and only
marks a target update as blocked if it really observed a stream mismatch.
Ref: https://github.com/coreos/zincati/pull/622#pullrequestreview-758708050
=> actor: handle staging failures in a more graceful way

Cargo.toml
related to https://github.com/coreos/afterburn/pull/625
=> cargo: enable debuginfo in the release profile

docs/_config.yml, docs/contributing.md, docs/development.md, docs/development/agent-actor-system.md, docs/development/cincinnati/protocol.md, docs/development/fleetlock/protocol.md, docs/development/os-metadata.md, docs/development/quickstart.md, docs/development/testing.md, docs/development/update-strategy-periodic.md, docs/index.md, docs/usage.md, docs/usage/agent-identity.md, docs/usage/auto-updates.md, docs/usage/configuration.md, docs/usage/logging.md, docs/usage/metrics.md, docs/usage/updates-strategy.md
docs: Do not convert -- & --- to en/em-dash
'--' is frequently used for command line options and was
thus\nincorrectly rendered as a special en-dash symbol.
---
docs: Remove default layout from front matter
No need to specify it as it is the default.
=> docs: Small docs fixes

Cargo.lock, Cargo.toml
Changes:
* update_agent: handle staging failures in a more graceful way
* update_agent: improve linewrapping of logout warning
* update_agent: log finalization success
* update_agent: log progress while waiting for the end of user sessions
* update_agent: record a denylist in the state of update agent
* update_agent: verify stream label on commit metadata before deploying
* metrics: hard fail on socket cleanup errors
* docs: small docs fixes
* cargo: enable debuginfo in release profile
* ci: bump linting toolchain to latest stable (1.56.0)
=> cargo: zincati release 0.0.24

.github/workflows/rust.yml
This bumps CI toolchains:
* lintings to 1.58 (latest stable)
* MSRV to 1.57 (currently shipping in F35)
=> ci: bump toolchains

Cargo.lock, Cargo.toml, src/cli/ex.rs, src/dbus/mod.rs
This updates both client and daemon logic to use the new zbus-2.x
API.
Closes: https://github.com/coreos/zincati/issues/709
=> cargo: port to zbus-2

Cargo.lock
This refreshes Cargo lockfile in order to shake off stale transitive
dependencies.
=> lockfile: refresh

dist/systemd/system/zincati.service
This tweaks the service unit ordering, adding explicit configuration for running after `multi-user.target`.
The service unit is currently pulled in by `multi-user.target`, which results in a implicit `Before` ordering being added by systemd. Unfortunately this may result in a dependency loop between `multi-user.target` and `boot-complete.target`, as the latter may need to start after the former.
Adding an explicit `After` statement here makes sure that both targets can be properly started in the relevant order, with Zincati queuing after both of them.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1298
Ref: https://lists.freedesktop.org/archives/systemd-devel/2022-September/048330.html
=> dist/systemd: add explicit ordering, after multi-user.target

.github/workflows/rust.yml, Cargo.lock, Cargo.toml
This updates the Cargo manifest to use the latest Rust edition.
As minor maintenance, it also bumps the MSRV in CI and refreshes the lockfile.
=> cargo: bump to 2021 edition 

Cargo.lock, Cargo.toml
Changes:
* cargo: bump to 2021 edition 
* cargo: update all dependencies to latest versions
* ci: bump toolchains
* dist/systemd: add explicit ordering, after multi-user.target
* tests/kola: re-arrange shared test helpers
=> cargo: zincati release 0.0.25

Cargo.lock, Cargo.toml, src/cli/agent.rs, src/cli/deadend.rs, src/cli/ex.rs, src/cli/mod.rs, src/config/mod.rs, src/main.rs
This reworks CLI handling logic, porting from the legacy `structopt`
library to the recommended `clap` v3.
Fixes: https://github.com/coreos/zincati/issues/832
=> cli: port from structopt to clap-3

src/cli/mod.rs, src/main.rs
This tweaks CLI handling logic in order to avoid using deprecated clap-v3 primitives.
It should make a future v4 update more straightforward.
=> cli: stop using deprecated clap-v3 features

src/cli/deadend.rs, src/cli/ex.rs, src/cli/mod.rs
This tweaks CLI handling logic in order to avoid using deprecated clap-v4 primitives.
It should make a future v5 update more straightforward.
=> cli: stop using deprecated clap-v4 features

docs/development/os-metadata.md, src/identity/mod.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mod.rs
This is aiming to increase compatibility of zincati with systems that aren't derived from Fedora CoreOS (e.g. IoT, desktop systems, etc.)
Additionally, even in the FCOS case, when one derives a container image from FCOS, the final build isn't generated by coreos-assembler and hence the ostree commit won't have this metadata.
In the end - I can't think of a use case for even trying to have zincati managing an image for a different architecture than the one it's compiled for.
So, copy the code I wrote for oci-spec-rs which maps from the Rust architecture to the GNU one.  xref
https://github.com/containers/oci-spec-rs/commit/52e450e631a212769df4dcd5b7904d942d246d24
=> Remove requirement for `coreos-assembler.basearch`

Cargo.toml
Having `lto = true` came from the first git commit to this repository. I suspect it was copied from elsewhere.
Having this enabled here makes an incremental (`CARGO_INCREMENTAL=1`) one-line change build take over a minute.
Disabling it makes that same one-line change take a second.
I think in general we should be deferring decisions like this to "outer" buildsystems; e.g. in Fedora Koji it makes sense to opt-in to full LTO.
=> build: Drop LTO by default

src/rpm_ostree/cli_status.rs, src/weekly/utils.rs
utils: Use explicit `u64::from`
Prep for a PR which may pull in the `glib` crate which has
a conflicting impl for this conversion (which is likely a bug).
---
status: Add a helper to extract the stream
Prep for handling the container case in
https://github.com/coreos/zincati/pull/878
---
=> status: preparatory work for stream detection from container

Cargo.lock, Cargo.toml, src/identity/mod.rs
This drops our duplicate code for finding the process architecture.
=> identity: use stream metadata crate for architecture detection

Cargo.lock, Cargo.toml, src/rpm_ostree/cli_deploy.rs
It's what's likely to be in `std` eventually.  Just a drive-by change.
=> Start a port to once_cell

dist/systemd/system/zincati.service, src/main.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mod.rs
This is part of https://github.com/coreos/fedora-coreos-tracker/issues/1263
We don't yet have an official stance on how zincati and custom container images interact.  Today, zincati just crash loops. This changes things so that we gracefully exit if we detect the booted system is using a container image origin.
(The code here isn't quite as clean as it could be; calling
`std::process::exit()` in the middle of the call chain isn't
elegant but doing better would require plumbing through an
`Option<T>` through many layers)
=> service: exit and prevent restarts if booted into a container image

src/config/fragments.rs, src/config/inputs.rs, src/identity/platform.rs, src/rpm_ostree/cli_status.rs, src/strategy/periodic.rs
Use the `std::fs` functions to read to a string or `Vec<u8>` directly; it's more efficient and less code.
Also in one place use `.map(BufReader::new)` which I find more... readable.
Not prep for anything, just a drive-by change since I was reading the code for other reasons.
=> Simplify read paths

src/rpm_ostree/actor.rs, src/rpm_ostree/cli_status.rs
The fact that we parsed this from JSON is just an implementation detail.
=> Drop "Json" suffix from rpm-ostree types

Cargo.toml
See https://github.com/coreos/cargo-vendor-filterer.
This project only targets Linux so we don't need any other platform dependencies.  Notably this obsoletes the manual step to strip all the static library files for the Windows crates.
```
$ find vendor-old -name '*.a' -delete
$ du -sh vendor-old vendor-new
208M	vendor-old
76M	vendor-new
```
=> cargo: add configuration for cargo-vendor-filterer

README.md, docs/_config.yml, docs/index.md
README & docs index: Remove Travis-CI badge
---
docs: Use upstream theme & update to 0.4.1
Use a fixed tag for the theme so that we can directly pull it from
upstream and skip vendoring the theme in the coreos org.
=> docs: Remove Travis-CI badge & Use upstream theme & update to 0.4.1

.github/workflows/rust.yml, Cargo.toml
Since we're using this elsewhere and it's needed for newer clap.
=> Bump MSRV to 1.64

dist/sysusers.d/50-zincati.conf
The sysusers docs say that lines starting with `#` are ignored, but I think there's RPM macros or something that trip up on this:
error: lua script failed: [string "add_sysuser"]:16: invalid sysuser type: #Zincati
3<        (%lua)
2<      (%add_sysuser)
error: lua script failed: [string "add_sysuser"]:16: invalid sysuser type: #Type
3<        (%lua)
2<      (%add_sysuser)
And systemd's sysusers dropins all also seem to have a space separator.
Let's add a space to see if it helps.
=> sysusers.d/50-zincati.conf: tweak comments

Cargo.lock, Cargo.toml
Closes: https://github.com/coreos/zincati/issues/1102
=> Release 0.0.26

dist/systemd/system/zincati.service, src/main.rs, src/rpm_ostree/cli_status.rs, src/rpm_ostree/mod.rs
The previous work resulted in an error, but let's just exit with status zero because otherwise we end up tripping up things like checks for failing units.
Anyone who has rebased into a container has very clearly taken explicit control over the wheel and there's no point in us erroring out.
=> Just exit normally when booted into a container

Cargo.lock, Cargo.toml
Changes:
* cargo: update all dependencies to latest versions
* cargo: bump libsystemd to 0.7.0 to fix fd leak
=> cargo: zincati release 0.0.27

src/update_agent/mod.rs
An issue as old as ~time~Fedora CoreOS is that when you're testing something related to updates, you want Zincati to reboot but because `cosa run` gives you an interactive session and you can't *not* have a session without losing the VM, you're stuck waiting for the 10 minutes grace period to expire.
Just add a hidden knob for this to make that scenario less painful.
The API is pretty much: when you're ready to have Zincati reboot, just `touch /run/zincati/override-interactive-check`.
=> update_agent: add hidden knob to override interactive session check

Cargo.lock, Cargo.toml
Changes:
- update_agent: add hidden knob to override interactive session check
- packit: add initial support
- cargo: update all dependencies to latest versions
- cargo: skip `zbus` update, see https://github.com/coreos/zincati/issues/1176
=> cargo: zincati release 0.0.28

.packit.yaml
As workaround for the issue that rust and packit are not currently compatible.
Xerf to https://src.fedoraproject.org/rpms/rust-openssh-keys/pull-request/9 and https://issues.redhat.com/browse/COS-2776
=> Add the action `prepare_files` to generate the new rpm file

Cargo.lock, Cargo.toml
Changes:
- cargo: update all dependencies to latest versions
- Add the action `prepare_files` to generate the new rpm file
=> cargo: zincati release 0.0.29

Makefile, dist/bin/zincati-update-now
This addresses the gap identified in
https://github.com/coreos/zincati/issues/498 in a blunt way by setting some runtime config knobs so Zincati in effect immediately downloads, deploys, and reboots the system.
The motivation to at least have this for now is
https://github.com/coreos/zincati/pull/1241, which will purposely break `rpm-ostree upgrade --bypass-driver`. But clearly the approach here is applicable regardless of whether the node has switched to OCI.
In the future, this may either get replaced by a proper `zincatictl` entrypoint, or by better integration into the system's update tooling (e.g. bootc), so that `bootc upgrade` does the right thing.
=> Add new `zincati-update-now` command

src/update_agent/mod.rs
loginctl no longer accepts the `--output=json` argument [1]. Adjust
here to use `--json=short` instead. Also, loginctl now outputs
`null` when there is no tty [2], so we can drop the custom
deserialize_systemd_tty_canonicalized deserializer.
[1] https://github.com/systemd/systemd/issues/34901
[2] https://github.com/systemd/systemd/commit/febfec0849616cb8d7d63f66c6dc05ca48a6a1e7
This should fix https://github.com/coreos/fedora-coreos-tracker/issues/1780
=> update_agent: adjust for recent changes in loginctl

src/strategy/periodic.rs
The log message reporting when the next update window is for the 'periodic' strategy does not format the minute nicely.  For instance, an update scheduled for `2:00` appears instead as `2:0` in the log, which may make new users think something is configured wrong.  This PR simply zero-pads the minute to ensure two digits are always displayed.
=> Fixed minute format in periodic update log

dist/bin/zincati-update-now
zincati-update-now: limit journal messages
The `-f` will show 10 previous lines which include some lines from
the previous instance of zincati. Let's just limit the messages to
the ones from this point forward.
---
zincati-update-now: don't block when restarting zincati
This allows us to more quickly fall through to the `journalctl`
following. I hit a case where it was taking some time for the
restart operation to complete (zincati was crashlooping) and
it would have helped to have already fallen through to the
journal watching.
---
zincati-update-now: give good error message when run without privs
This is a bit better than what currently happens.
=> quality of life improvements for zincati-update-now

src/cincinnati/mod.rs
In [1] i reworked how cincinnati nodes are turned into deployments for comparing them. I also simplified this logic to match already existing deployments with cincinnati nodes.
Basically the cincinnati node is turned into a deployment looking like:
```
Release {
version: "42.20250410.3.1",
payload: Checksum("e057a84658cd114c1fa8a944d8fe3de93f5413c0fbe3f1fabc737cc04bbd749b"),
age_index: Some(144) }
```
And a local deployment looks like:
```
Release {
version: "41.20250315.3.0",
payload: Checksum("3c6418b40e2c7fe4605ff1fa744a845caadd50e10bd31aab14e059b529f49c98"),
age_index: None }
```
Obviously, there is no age_index value for a local deployement as it's a cinncinati thing. Thus, a local deployment won't ever be equal to a cinncinati node.
Fix thi slogic by extracting the `Payload` enum …
=> cincinnati: fix updates nodes comparison logic
